# Meu primeiro Markdown
## Python

In [ ]:
nome = "joaquin"
idade = 34
valor_em_carteira = 345.99
vip = True

print(nome)

In [1]:
def soma_dois_valores(primeiro,segundo):
    resultado = primeiro + segundo 
    return resultado

valor_1 = 10
valor_2 = 20

soma = soma_dois_valores(valor_1,valor_2)

print(soma)


30


In [6]:
lista_clientes = ["joaquina","jose","joão","Maria"]
lista_produtos = ["Maça","Banana","Chocolate"]

lista_clientes.append("Roberta")
print(lista_clientes[4])

Roberta


In [8]:
lista_vendas = []

venda = ("banana",4,8.50)

lista_vendas.append(venda)
print(lista_vendas)


[('banana', 4, 8.5)]


In [ ]:
cliente_1 = {
     "nome":"joaquin",
     "idade":34,
     "vip" : True,
     "carteira":345.99
}

cliente_2 = { 
     "nome":"roberta", #chave e valor pode modificar o valor ma a chave nao 
     "idade":24,
     "vip" : False,
     "carteira":1245.99
}
cliente_2["idade"] = 25

lista_clientes = [cliente_1,cliente_2]
print(lista_clientes)
print(cliente_1["carteira"])

In [4]:
import math

print(math.pow(3,4))
print(math.tan(2))

81.0
-2.185039863261519


In [ ]:
import numpy as np 

numpy_array = np.arange(0,1_000_000 + 1 , dtype = "int64")
#Tempo de execuçao : 0.008s
## memoria utilizada:7.5 MiB

# Tipos e Acesso aos Elementos de um Array

In [ ]:
# criando um array
import numpy as np

arr = np.array([1,2,3,4,5])
print(f"elementos:{arr},Tipo dos elementos:{arr.dtype} , tamanho do array:{arr.shape}")

##Criando uma matrix 
matrix = np.arange(1.,10).reshape((3,3))
print(matrix)
print (f"tipos dos elementos:{matrix.dtype},Dimensoes da matriz:{matrix.shape}")

## Acessando a 2 linha :
linha = matrix[1]
print(linha)

## Acessando a 1 coluna:
coluna = matrix[:,1]
print(coluna)



In [16]:
import numpy as np

a = np.array([1.0,2.0,3.0])
b = 2.0
resultado = a * b
print(resultado)

[2. 4. 6.]


# Multiplicacao utilizando apenas listas em Python

In [21]:
import numpy as np

A = np.array([[1, 2], [3,4], [5,6]])
B = np.array([[1], [2]])
print(A)
print(B)


#Multiplicação das Matrizes

D = A @ B
print(D)

[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]]
[[ 5]
 [11]
 [17]]


In [ ]:
import numpy as np

N = 500

A = np.arange(N*N , dtype = "int64").reshape(N,N)
B = A * 2

C = A @ B

print(C)

# Pandas:Series e DataFrames 


# Series

In [ ]:
import pandas as pd
cidades = [
    "Sao paulo (SP)",
    "Rio de Janeiro(RJ)",
    "Brasilia(DF)",
    "Fortaleza(CE)",
    "Salvador(BA)",
    "Belo horizonte",
    "Manaus(AM)",
    "Curitiba(PR)", 
]

populacoes = [
    12,
    6.5,
    3,
    2.4,
    2.4,
    2.3,
    2,
    1.7
   
]

cidades_series = pd.Series(cidades)
print(cidades_series)

populacoes_series = pd.Series(populacoes)
print(populacoes_series)

print(cidades_series[3])
print(cidades_series[3:5])
print(populacoes_series.max())#numero mais alto
print(populacoes_series.mean())#media



# DataFrames

In [ ]:
import pandas as pd

cidades_populosas = pd.DataFrame({"cidade": cidades_series,"populacao em milhoes":populacoes_series})
cidades_populosas
